dist: trusty

language: cpp

compiler:
 - gcc

before_install:
 - sudo apt-get -y install dh-autoreconf
 - git clone http://github.com/FantasticOnAStick/foas_common.git

script:
 - mkdir build
 - cd build
 - cmake ..
 - make
